# Generated by Django 3.0 on 2019-12-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('document', models.ImageField(upload_to='../files/signature/')),
                ('signature_image', models.TextField()),
                ('sender_email', models.EmailField(blank=True, default='', max_length=255)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=255)),
                ('creation_date', models.DateField(null=True)),
                ('date_signature', models.DateField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
