# Generated by Django 3.0 on 2019-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0002_auto_20191216_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='document',
            field=models.ImageField(upload_to='app/src/files/signature/'),
        ),
    ]
