# Generated by Django 3.0 on 2019-12-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0005_auto_20191216_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='document',
            field=models.FileField(upload_to='files/signature'),
        ),
    ]
