# Generated by Django 3.0 on 2019-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0006_auto_20191216_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
