# Generated by Django 3.0.1 on 2019-12-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0007_auto_20191220_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='document',
            field=models.FileField(upload_to='signature'),
        ),
    ]
