# Generated by Django 3.0.1 on 2020-01-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0008_auto_20191224_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='full_name_recipient',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='signature',
            name='full_name_sender',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
