# Generated by Django 2.2.7 on 2019-11-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('code', models.IntegerField()),
                ('id_cci', models.IntegerField(default=0)),
                ('courriel', models.EmailField(blank=True, default='', max_length=255)),
                ('date_creation', models.DateField(null=True)),
                ('fax', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('siret', models.CharField(blank=True, default='', max_length=14)),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('url_logo', models.URLField(blank=True, default='', max_length=255)),
                ('url_site_web', models.URLField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['code', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CFE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=5)),
                ('courriel', models.EmailField(blank=True, default='', max_length=255)),
                ('libelle', models.CharField(max_length=120)),
                ('libelle_court', models.CharField(blank=True, default='', max_length=50)),
                ('type_cfe', models.CharField(choices=[('C', 'CCI'), ('U', 'URSSAF'), ('G', 'GREFFE')], max_length=1)),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('fax', models.CharField(blank=True, default='', max_length=50)),
                ('url_logo', models.URLField(blank=True, default='', max_length=255)),
                ('url_site_web', models.URLField(blank=True, default='', max_length=255)),
                ('cci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfes', to='api.CCI')),
            ],
            options={
                'ordering': ['code', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='CodePostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=2)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(blank=True, default='', max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, default='', max_length=2)),
                ('code_consulaire', models.CharField(max_length=2)),
                ('libelle', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Responsabilite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('signature', models.CharField(blank=True, default='', max_length=255)),
                ('cci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsabilites', to='api.CCI')),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsabilites', to='api.Personne')),
                ('qualite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsabilites', to='api.Qualite')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('ancien_nom', models.CharField(blank=True, default='', max_length=100)),
                ('annee_inde', models.IntegerField(blank=True, null=True)),
                ('code_actualite', models.IntegerField(blank=True, null=True)),
                ('code_ancien_pays', models.CharField(blank=True, default='', max_length=5)),
                ('codecfe', models.CharField(blank=True, default='', max_length=3)),
                ('codeiso2', models.CharField(blank=True, default='', max_length=2)),
                ('codeiso3', models.CharField(blank=True, default='', max_length=3)),
                ('code_num3', models.IntegerField()),
                ('code_officiel_geo', models.CharField(blank=True, default='', max_length=5)),
                ('code_pays_ratt', models.CharField(blank=True, default='', max_length=5)),
                ('esteee', models.BooleanField()),
                ('estue', models.BooleanField()),
                ('libelle', models.CharField(max_length=100)),
                ('libelle_complet', models.CharField(blank=True, default='', max_length=100)),
                ('nationalite', models.CharField(blank=True, default='', max_length=100)),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='api.Continent')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=3)),
                ('libelle', models.CharField(max_length=100)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='api.Region')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('article', models.CharField(blank=True, default='', max_length=10)),
                ('code', models.CharField(max_length=5)),
                ('libelle', models.CharField(max_length=100)),
                ('cci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes', to='api.CCI')),
                ('cfe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes', to='api.CFE')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communes', to='api.Departement')),
            ],
            options={
                'ordering': ['code', 'libelle'],
            },
        ),
        migrations.AddField(
            model_name='cfe',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfes', to='api.Pays'),
        ),
        migrations.AddField(
            model_name='cci',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccis', to='api.Pays'),
        ),
        migrations.AddField(
            model_name='cci',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccis', to='api.Region'),
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('code_postal', models.CharField(blank=True, default='', max_length=5)),
                ('commune', models.CharField(blank=True, default='', max_length=100)),
                ('complement', models.CharField(blank=True, default='', max_length=100)),
                ('distribution_speciale', models.CharField(blank=True, default='', max_length=100)),
                ('indice_repetition', models.CharField(blank=True, default='', max_length=10)),
                ('nom_voie', models.CharField(blank=True, default='', max_length=100)),
                ('numero_voie', models.CharField(blank=True, default='', max_length=20)),
                ('type_adresse', models.CharField(choices=[('P', 'Adresse postale'), ('F', 'Adresse de facturation')], default='P', max_length=1)),
                ('type_voie', models.CharField(blank=True, default='', max_length=20)),
                ('cci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='api.CCI')),
                ('cfe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='api.CFE')),
            ],
        ),
        migrations.CreateModel(
            name='Acheminement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('libelle', models.CharField(max_length=100)),
                ('code_postal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acheminements', to='api.CodePostal')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acheminements', to='api.Commune')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.AddIndex(
            model_name='acheminement',
            index=models.Index(fields=['id'], name='acheminements_id_1'),
        ),
        migrations.AddIndex(
            model_name='acheminement',
            index=models.Index(fields=['-id'], name='acheminements_id_2'),
        ),
        migrations.AddIndex(
            model_name='acheminement',
            index=models.Index(fields=['libelle'], name='acheminements_libelle_1'),
        ),
        migrations.AddIndex(
            model_name='acheminement',
            index=models.Index(fields=['-libelle'], name='acheminements_libelle_2'),
        ),
    ]
