# Generated by Django 2.2.7 on 2019-11-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(blank=True, default='', max_length=100)),
                ('prenom', models.CharField(blank=True, default='', max_length=100)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction_generique', models.CharField(blank=True, default='', max_length=5)),
                ('fonction_exacte', models.CharField(blank=True, default='', max_length=250)),
                ('date_debut_fonction', models.CharField(blank=True, default='', max_length=10)),
                ('date_fin_fonction', models.CharField(blank=True, default='', max_length=10)),
                ('titre_politesse', models.CharField(blank=True, default='', max_length=3)),
                ('tel_fixe', models.CharField(blank=True, default='', max_length=15)),
                ('tel_mobile', models.CharField(blank=True, default='', max_length=15)),
                ('service', models.CharField(blank=True, default='', max_length=100)),
                ('expertise', models.CharField(blank=True, default='', max_length=100)),
                ('domaine_metier', models.CharField(blank=True, default='', max_length=100)),
                ('centres', models.CharField(blank=True, max_length=100)),
                ('raison_sociale', models.CharField(blank=True, default='', max_length=100)),
                ('n_siret', models.CharField(blank=True, default='', max_length=30)),
                ('BP', models.CharField(blank=True, default='', max_length=100)),
                ('CP', models.CharField(blank=True, default='', max_length=10)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('fax', models.CharField(blank=True, default='', max_length=100)),
                ('adress', models.CharField(blank=True, default='', max_length=100)),
                ('Complement_adresse', models.CharField(blank=True, max_length=100)),
                ('type_organisme', models.CharField(blank=True, default='', max_length=100)),
                ('enseigne', models.CharField(blank=True, default='', max_length=100)),
                ('complement_adresse', models.CharField(blank=True, max_length=100)),
                ('sous_type', models.CharField(blank=True, max_length=100)),
                ('secteur_activite', models.CharField(blank=True, default='', max_length=100)),
                ('Code_APE', models.CharField(blank=True, max_length=100)),
                ('effectif', models.CharField(blank=True, max_length=100)),
                ('nombre_ressortissants', models.CharField(blank=True, default='', max_length=100)),
                ('id_annuaire', models.CharField(blank=True, default='', max_length=100)),
                ('source_import', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('departement', models.CharField(blank=True, default='', max_length=100)),
                ('matricule', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['matricule'],
            },
        ),
    ]
