# Generated by Django 2.2.7 on 2019-11-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='Complement_adresse',
        ),
        migrations.AddField(
            model_name='personnel',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='radiation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='site',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personnel',
            name='tweeter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_debut_fonction',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_fin_fonction',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fonction_generique',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='tel_fixe',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='tel_mobile',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='titre_politesse',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
