# Generated by Django 2.2.7 on 2019-11-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191121_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='fonction_exacte',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
